# Generated by Django 5.1 on 2024-08-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_bookmark_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True, editable=False, max_length=100, unique=True
            ),
        ),
    ]
