# Generated by Django 5.1 on 2024-09-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "billing_period",
                    models.CharField(default="Per Month", max_length=50),
                ),
                (
                    "features",
                    models.TextField(help_text="Enter each feature on a new line."),
                ),
            ],
        ),
    ]
