# Generated by Django 5.1 on 2024-09-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_statistic"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="default.jpg", upload_to="about_us_images/"
                    ),
                ),
                ("title", models.CharField(default="About Our Dojo", max_length=255)),
                (
                    "description",
                    models.TextField(
                        default="Our dojo is a place where karate enthusiasts of all levels come to train and improve. With a team of skilled instructors and a rich tradition of martial arts, we are committed to helping you achieve your karate goals."
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        default=list,
                        help_text='A list of features, e.g., ["World-class training facilities", "Experienced and certified instructors", "Personalized training programs"]',
                    ),
                ),
            ],
        ),
    ]
